package rw;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * rwSyllableTreatmentDialog.java
 *
 * Created on Feb 1, 2014, 6:38:11 PM
 */
/**
 *
 * @author tedr
 */
public class rwSyllableTreatmentDialog extends javax.swing.JPanel {

    /** Creates new form rwSyllableTreatmentDialog */
    public rwSyllableTreatmentDialog() {
        initComponents();
    }

    public rwSyllableTreatmentDialog(int num, boolean efficiency){
        initComponents();
        maximumSyllablesSpinner.setValue(num);
        syllabicEfficiencyCheck.setSelected(efficiency);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        maximumSyllablesSpinner = new javax.swing.JSpinner();
        syllabicEfficiencyCheck = new javax.swing.JCheckBox();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Maximum Syllables");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 0);
        add(jLabel1, gridBagConstraints);

        maximumSyllablesSpinner.setModel(new javax.swing.SpinnerNumberModel(4, 1, 6, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(maximumSyllablesSpinner, gridBagConstraints);

        syllabicEfficiencyCheck.setText("Use Syllabic Efficiency");
        syllabicEfficiencyCheck.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        syllabicEfficiencyCheck.setIconTextGap(25);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        add(syllabicEfficiencyCheck, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JSpinner maximumSyllablesSpinner;
    public javax.swing.JCheckBox syllabicEfficiencyCheck;
    // End of variables declaration//GEN-END:variables
}
