/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RwConsonantDialog.java
 *
 * Created on Jan 26, 2011, 1:02:15 PM
 */

package rw;


import javax.swing.table.*;
import java.util.*;
/**
 *
 * @author Ted
 */
public class RwVowelConsonantDialog extends javax.swing.JDialog {

    /** Creates new form RwConsonantDialog */
    public RwVowelConsonantDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    public RwVowelConsonantDialog(java.awt.Frame parent, boolean modal, Vector data){
        super(parent,modal);
        initComponents();
        setLocationRelativeTo(parent);
        dtm=(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(data.size());
        for(int a=0; a<data.size();a++){
            dtm.setValueAt(data.elementAt(a), a, 1);
        }
        updateTable();
        jTextField1.setText(data.size()+"");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtm = new javax.swing.table.DefaultTableModel();
        rwCellRenderer1 = new rw.RwCellRenderer();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        downCharacterButton = new javax.swing.JButton();
        upCharacterButton = new javax.swing.JButton();
        upPageButton = new javax.swing.JButton();
        downPageButton = new javax.swing.JButton();
        currentCharField = new javax.swing.JTextField();

        dtm.addTableModelListener(new javax.swing.event.TableModelListener() {
            public void tableChanged(javax.swing.event.TableModelEvent evt) {
                dtmTableChanged(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Number");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("LCS-ConstructorII", 0, 24));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Unicode", "Visible"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setCellRenderer(rwCellRenderer1);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update Table");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        downCharacterButton.setText("<");
        downCharacterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downCharacterButtonActionPerformed(evt);
            }
        });

        upCharacterButton.setText(">");
        upCharacterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upCharacterButtonActionPerformed(evt);
            }
        });

        upPageButton.setText(">>");
        upPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upPageButtonActionPerformed(evt);
            }
        });

        downPageButton.setText("<<");
        downPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downPageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(okButton)
                                .addGap(107, 107, 107)
                                .addComponent(clearButton))
                            .addComponent(downPageButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(currentCharField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(downCharacterButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(upCharacterButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(upPageButton)
                                .addGap(33, 33, 33))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelButton)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(updateButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(downCharacterButton)
                    .addComponent(upPageButton)
                    .addComponent(upCharacterButton)
                    .addComponent(downPageButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentCharField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(clearButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        chosenOption = this.CANCEL_OPTION;
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        dtm=(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(Integer.parseInt(jTextField1.getText()));
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        chosenOption = this.OK_OPTION;
        this.setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        updateTable();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void updateTable(){
        dtm=(DefaultTableModel)jTable1.getModel();
        for(int a=0;a<dtm.getRowCount();a++){
            Object val0=dtm.getValueAt(a, 0);
            Object val1=dtm.getValueAt(a, 1);
            String vs0= (val0==null)? "":val0.toString();
            String vs1= (val1==null)? "":val1.toString();
            if(!("").equals(vs0)){
                String s=(String)dtm.getValueAt(a, 0);
                String[] sa=s.split("u");
                String v = "";
                for(int b=1;b<sa.length;b++){
                    char ch = (char)Integer.parseInt(sa[b],16);
                    v = v + ch;
                }
                dtm.setValueAt(v, a, 1);
            } else if(!("").equals(vs1)){
                String s=(String)dtm.getValueAt(a, 1);
                String v="";
                for(int b=0;b<s.length();b++){
                    String u = "0000" + Integer.toHexString(s.charAt(b));
                    v += "u" + u.substring(u.length()-4);
                }
                dtm.setValueAt(v, a, 0);
            }
        }
    }

    private void dtmTableChanged(javax.swing.event.TableModelEvent evt) {//GEN-FIRST:event_dtmTableChanged
       //method was added, but it never gets called!!
    }//GEN-LAST:event_dtmTableChanged

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        dtm=(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        dtm.setRowCount(Integer.parseInt(jTextField1.getText()));
    }//GEN-LAST:event_clearButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        currentCharField.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0)+"");
    }//GEN-LAST:event_jTable1MouseClicked

    private void downPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downPageButtonActionPerformed
        String cv=currentCharField.getText();
        cv=cv.substring(1);
        int val = Integer.parseInt(cv,16);
        val -= 256;
        if(val <= 0){
            val = 65535 - val;
        }
        cv = Integer.toHexString(val);
        cv = ("0000" +  cv).substring(cv.length());
        jTable1.setValueAt("u" + cv, jTable1.getSelectedRow(), 0);
        currentCharField.setText("u" + cv);
        updateButtonActionPerformed(evt);
    }//GEN-LAST:event_downPageButtonActionPerformed

    private void downCharacterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downCharacterButtonActionPerformed
        String cv=currentCharField.getText();
        cv=cv.substring(1);
        int val = Integer.parseInt(cv,16);
        val -= 1;
        if(val <= 0){
            val = 65535 - val;
        }
        cv = Integer.toHexString(val);
        cv = ("0000" +  cv).substring(cv.length());
        jTable1.setValueAt("u" + cv, jTable1.getSelectedRow(), 0);
        currentCharField.setText("u" + cv);
        updateButtonActionPerformed(evt);
    }//GEN-LAST:event_downCharacterButtonActionPerformed

    private void upCharacterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upCharacterButtonActionPerformed
        String cv=currentCharField.getText();
        cv=cv.substring(1);
        int val = Integer.parseInt(cv,16);
        val += 1;
        if(val >= 65535){
            val = 0 ;
        }
        cv = Integer.toHexString(val);
        cv = ("0000" +  cv).substring(cv.length());
        jTable1.setValueAt("u" + cv, jTable1.getSelectedRow(), 0);
        currentCharField.setText("u" + cv);
        updateButtonActionPerformed(evt);
    }//GEN-LAST:event_upCharacterButtonActionPerformed

    private void upPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upPageButtonActionPerformed
        String cv=currentCharField.getText();
        cv=cv.substring(1);
        int val = Integer.parseInt(cv,16);
        val += 256;
        if(val >= 65535){
            val -= 65535;
        }
        cv = Integer.toHexString(val);
        cv = ("0000" +  cv).substring(cv.length());
        jTable1.setValueAt("u"+cv, jTable1.getSelectedRow(), 0);
        currentCharField.setText("u" + cv);
        updateButtonActionPerformed(evt);
    }//GEN-LAST:event_upPageButtonActionPerformed

    public Vector getData(){
        Vector v=new Vector();
        for(int a=0;a<dtm.getRowCount();a++){
            v.add(dtm.getValueAt(a, 1));
        }
        return v;
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RwVowelConsonantDialog dialog = new RwVowelConsonantDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public int getChosenOption(){
        return chosenOption;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField currentCharField;
    private javax.swing.JButton downCharacterButton;
    private javax.swing.JButton downPageButton;
    private javax.swing.table.DefaultTableModel dtm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton okButton;
    private rw.RwCellRenderer rwCellRenderer1;
    private javax.swing.JButton upCharacterButton;
    private javax.swing.JButton upPageButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
    public static int CANCEL_OPTION = -1;
    public static int OK_OPTION = 1;
    public int chosenOption = this.CANCEL_OPTION;
}
